name: Build OpenWrt x86_64

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger - success]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: false
  TZ: Asia/Shanghai
  FILE_NAME: OpenWrt-x86_64-firmware

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          chmod +x free_disk_space.sh
          ./free_disk_space.sh
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get update
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone source code # 克隆的源代码
        id: openwrt
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          useVersionInfo=$(git show -s --date=short --format="Author:%an<br/>date:%cd<br/>commit:%s<br/>commit hash:%H")
          echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
          echo "DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
          echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          tag_name: ${{ format('{0}/{1}', env.DATE, env.git_hash) }}
          release_name: ${{ env.DATE }}
          body: |
            当前使用版本：
            ${{ env.useVersionInfo }}
          draft: false
          prerelease: false

      - name: Update feeds
        run: |
          cd openwrt
          sed -i 's/\#src-git helloworld/\src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load custom configuration # 加载自定义配置
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_SH
          cd openwrt
          ../$DIY_SH

      - name: Generate configuration file
        run: |
          cd openwrt
          make defconfig

      - name: Make download
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Check space usage
        if: (!cancelled())
        run: df -hT

      - name: Compile firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          #make -j1 || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        id: organize
        run: |
          find openwrt/bin/targets/ -type d -name "packages" | xargs rm -rf {}
          mv openwrt/.config  openwrt/bin/targets/*/*
          cd openwrt/bin/targets/*/*
          echo "FIRMWARE=$(pwd)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ${{ env.FIRMWARE }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.RELEASES_TOKEN }}
          file: ${{ env.FIRMWARE }}/* # https://www.npmjs.com/package/glob
          tag: ${{ format('{0}/{1}', env.DATE, env.git_hash) }}
          overwrite: true
          file_glob: true
      
      - name: WeChat notification
        run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=${{ env.FILE_NAME }}编译完成
