name: Repository dispatch
on:
  workflow_run:
    workflows: ["trigger"]
    types: [completed]
    
jobs:
  workflow-dispatch:
    name: repo dispatch event with conclusion 
    runs-on: windows-2019
    steps:
      - name: repo dispatch
        uses: tonyhallett/workflow-run-conclusion-dispatch-action@v1.0.0
        with:
            GITHUB_PAT: ${{ secrets.RELEASES_TOKEN }}
